### ISSUE TITLE
It would be great if response type were something we could pattern-match over

### ISSUE THREAD

**Issue by Trevoke** [myfreeweb/httpotion#110]
So for instance

```elixir
{:ok, resp = HTTPotionResponse%{}} = HTTPotion.get("www.foo.bar")
```

It would help us get a lot more value out of this tool.

**Comment by myfreeweb** [comment]
You can pattern match on structs.

As for returning an exception instead of a value when connection fails… you're about four years too late with this :) I realize that I probably shouldn't have used exceptions, but back then I thought they were more idiomatic Elixir. I'm not going to commit such huge changes to the public API now.

**Comment by Trevoke** [comment]
That's what new major versions are for :)

**Comment by myfreeweb** [comment]
Yeah. I don't want to release a new one. I think the API is fine as it is.

**Comment by Trevoke** [comment]
I can't blame you; it's your project :)

I have in the meanwhile found `HTTPoison` which seems to behave the way I like, so I think I will use it.

Thank you for entertaining my requests!

**Comment by myfreeweb** [comment]
oh wow, they not only replaced ibrowse with hackney, but also did that. Nice :)
