### ISSUE TITLE
Does HTTPotion Support SNI?

### ISSUE THREAD

**Issue by Preen** [myfreeweb/httpotion#119]
Getting handshake failure when I try to use it against aws cloudfront which currently (if you pick the free version of certificate) only allows clients that supports SNI.

`%HTTPotion.ErrorResponse{message: "{:tls_alert, 'handshake failure'}"}`

**Comment by myfreeweb** [comment]
It should work I think…

What Erlang version are you using? Are you using an HTTP proxy? Can you connect to that domain with raw ssl module? like `:ssl.connect('example.com', 443, [])`

**Comment by Preen** [comment]
I had to specify the ssl version. As mentioned [here](https://github.com/edgurgel/httpoison/issues/164) 

```
# Either use this

HTTPoison.get("https://example.com/", [], [ssl: [{:versions, [:'tlsv1.2']}]])

# or worst case:

HTTPoison.get("https://example.com/", [], [ssl: [{:verify, :verify_none}]])
```

**Comment by myfreeweb** [comment]
Damn, Erlang ssl's behavior is so weird, why does it only automatically set SNI if you force TLS 1.2 o_0

You can probably do something like that:

```elixir
HTTPotion.get("https://example.com/", [ibrowse: [ssl_options: [{:versions, [:'tlsv1.2']}]]])
```

But it seems like you can also pass the hostname as the `server_name_indication` option instead of TLS 1.2. HTTPotion should automatically do this. I'll implement that soon.

**Comment by myfreeweb** [comment]
Done. SNI should work automatically on current master.
